version: '3.9'
services:
  app:
    build:
      context: .
    command: npm run deploy:run-all
    environment:
      NODE_ENV: production
      PORT: 3000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
